config: finetune_cifar100_25cl.yml
dataset: cifar100
classes_per_task: 25
backbone: resnet18
strategy: finetune
epochs: 60
batch: 128
buffer: 1000
ewc: 10.0
output: runs/finetune_clases-25_cifar100_epochs--60
img_size: 224
duracion_segundos: 6675.88
duracion_hms: '1:51:15'
