config: finetune_cifar10_2cl.yml
dataset: cifar10
classes_per_task: 2
backbone: resnet18
strategy: finetune
epochs: 30
batch: 128
buffer: 1000
ewc: 10.0
output: runs/finetune_clases-2_cifar10_epochs--30
img_size: 224
duracion_segundos: 3117.55
duracion_hms: 0:51:57
