config: finetune_cifar10_5cl.yml
dataset: cifar10
classes_per_task: 5
backbone: resnet18
strategy: finetune
epochs: 30
batch: 128
buffer: 1000
ewc: 10.0
output: runs/finetune_clases-5_cifar10_epochs--30
img_size: 224
duracion_segundos: 1859.8
duracion_hms: 0:30:59
