config: finetune_cifar10_5cl.yml
dataset: cifar10
classes_per_task: 5
backbone: resnet18
strategy: finetune
epochs: 6
batch: 64
buffer: 1000
ewc: 10.0
output: runs/finetune_clases-5_cifar10
img_size: 224
