config: replay_cifar10_2cl.yml
dataset: cifar10
classes_per_task: 2
backbone: resnet18
strategy: replay
epochs: 30
batch: 128
buffer: 8000
ewc: 10.0
output: runs/replay_clases-2_cifar10_epochs--30
img_size: 224
duracion_segundos: 4865.8
duracion_hms: '1:21:05'
