method: runs/replay_clases-5_cifar10
modes:
  - type: intra
    ckpt_task: 1
    task_a: 0
    task_b: 1
    k: 3
    samples: 1000
    json_out: sim_replay_t1_0v1.json
  - type: inter
    ckpt_a: 0
    ckpt_b: 1
    task: 1
    k: 3
    samples: 800
    json_out: sim_replay_t0v1_task1.json
