config: finetune_cifar10_2cl.yml
dataset: cifar10
classes_per_task: 2
backbone: resnet18
strategy: finetune
epochs: 2
batch: 128
buffer: 1000
ewc: 10.0
output: runs/finetune_clases-2_cifar10_epochs-2
img_size: 224
duracion_segundos: 162.67
duracion_hms: 0:02:42
