config: finetune_cifar10_10cl.yml
dataset: cifar10
classes_per_task: 10
backbone: resnet18
strategy: finetune
epochs: 30
batch: 128
buffer: 1000
ewc: 10.0
output: runs/finetune_clases-10_cifar10_epochs--30
img_size: 224
duracion_segundos: 1783.11
duracion_hms: 0:29:43
